### ISSUE TITLE
existing files not skipped

### ISSUE THREAD

**Issue by stsp** [dosemu2/install-otherdos#6]
Running install3rdpartydos the second time,
gives this:
```
Continuing with existing file set in: /home/stas/.cache/dosemu/svardos
Extracting /home/stas/.cache/dosemu/svardos/svardos-dosemu.zip to /home/stas/.dosemu/install/svardos/drive_c
replace /home/stas/.dosemu/install/svardos/drive_c/INSTALL.BAT? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C
```

@jschwartzenberg could you please take a look?

**Comment by jschwartzenberg** [comment]
Supplying either `-n` or `-o` to `unzip` here would work. What I did for `install-freedos` was implementing the unzipping in Python so that the script could handle the various cases in case files matched or did not match. If I remember correctly, when the file in the archive matches the file on-disk it simply continues to the next file, if there is a mismatch, the script is aborted, the user is pointed to the file that is different with a suggestion to remove things in case they want reinstall.

Shall we do the same thing here? It would also drop the dependency to `unzip`.

**Comment by jschwartzenberg** [comment]
> Of course that would be cool.
> If python replaces external utils,
> I am all for that.

Yeah it was also one of the reasons for me to switch from shell scripts to Python scripts. Apart from the shell scripts becoming hard to understand, I saw that Python could provide a lot through libraries. These subprocess calls you're addressing are all remnants from the shell script versions of these scripts. I wanted to provide something working first though and clean up in steps putting prio on features/clean-ups as would be requested. The very first Python versions consisted mainly of subprocess calls.

Maybe it would be interesting to port the `dosemu` launcher script to Python as well down the line.

**Comment by stsp** [comment]
So does svardos now bypass the
extra install stage?

**Comment by jschwartzenberg** [comment]
Ah no, I did not look at this. To me it seems surprising this was made up at all as one could just create a 'post-install' zip afaics and this had best be solved by providing another zip file. @mateuszviste do you know the reason behind the extra step?

**Comment by stsp** [comment]
I think svardos uses his own package manager,
so maybe that extra step is required to populate
its database?

**Comment by mateuszviste** [comment]
> I think svardos uses his own package manager,
> so maybe that extra step is required to populate
> its database?

That's correct. The script only deploys the set of system packages, and then at first boot they are installed by SvarDOS' package installer (pkg).

**Comment by jschwartzenberg** [comment]
So no the script aborts, because I guess it sees the "empty" database file from the zip differs from the populated one after the installation. How should a second run of the script behave? Is there an intention to update the ZIP file in the future? For other DOSes another version would be installed separately.

**Comment by stsp** [comment]
> "empty" database file from the zip

I suppose it should be excluded from
extraction (or removed after).

**Comment by mateuszviste** [comment]
> How should a second run of the script behave?

It should do nothing.

> Is there an intention to update the ZIP file in the future?

Yes, but this would only apply to new installations. Existing installations should be kept up to date through the internal SvarDOS tools. This mimics the way hardware-based installations behave.

**Comment by stsp** [comment]
> It should do nothing.

Probably we just need some
--reinstall option then. If something
goes wrong on a DOS side, user
should still be able to recover.
